<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\UploadedFile;

/**
 * This is the model class for table "books".
 *
 * @property integer $id
 * @property string $name
 * @property string $preview
 * @property integer $date_create
 * @property integer $date_update
 * @property integer $date
 * @property integer $author_id
 *
 * @property Authors $author
 */
class Books extends \yii\db\ActiveRecord
{

    public $image;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create', 'name'], 'required'],
            [['date_create', 'date_update', 'date',  'author_id'], 'integer'],
            [['name', 'preview'], 'string', 'max' => 60],
            [['image'], 'image', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'preview' => 'Превью',
            'image' => 'Image',
            'date_create' => 'Date Create',
            'date_update' => 'Дата добавления книги',
            'date' => 'Дата выхода книги',
            'author_id' => 'Автор книги',
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_create',
                'updatedAtAttribute' => 'date_update',
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Authors::className(), ['id' => 'author_id']);
    }


    public function beforeValidate()
    {
        $this->date = strtotime($this->date);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function getPreviewUrl()
    {
        return Yii::getAlias('@img') . '/' . $this->preview;
    }

    public function getLightBox()
    {
        return "<a href='" . $this->getPreviewUrl() . "' rel='lightbox'>
                   <img width='40' height='40' src='" . $this->getPreviewUrl() . "'>
               </a>";
    }

    public function upload()
    {
        $this->image = UploadedFile::getInstance($this, 'image');

        if(is_object($this->image)){
            $this->preview = $this->image->baseName    . '.' . $this->image->extension;
            $this->image->saveAs($this->getPreviewUrl());
            $this->image = '';
        }
    }
    
    public static function getGridColumns()
    {
        return [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            [
                'attribute' => 'preview',
                'format'    => 'raw',
                'value'     => function ($model) {
                    return $model->getLightBox();
                },
            ],

            [
                'attribute' => 'date_update',
                'format'    => 'date',

            ],

            [
                'attribute' => 'date',
                'format'    => 'date',

            ],
            [
                'attribute' => 'author_id',
                'format'    => 'raw',
                'value'     => function ($model) {
                    return $model->author->getName();
                },
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'header'=> 'Кнопки действий'
            ],
        ];
    }
}

